/**
 * Trimmed Mapbox Streets v8 source layer field definitions
 * Only includes fields with enumerated values for filtering and styling
 *
 * Omitted for brevity:
 * - Fields with unbounded string/number values (name, ref, house_num, height, etc.)
 * - Localized name fields (name_de, name_en, name_es, etc.) - these exist but have no fixed values
 * - Description fields that just repeat the key name
 * - iso_3166_2 field (always unbounded string)
 */

// Common field that appears identically in 13 layers
const ISO_3166_1_FIELD = {
  values: [
    'EG',
    'ET',
    'CD',
    'ZA',
    'TZ',
    'KE',
    'SD',
    'UG',
    'MA',
    'DZ',
    'GH',
    'CI',
    'CM',
    'MG',
    'MZ',
    'NG',
    'NE',
    'BF',
    'MW',
    'ML',
    'TD',
    'SN',
    'AO',
    'ZW',
    'CN',
    'IN',
    'ID',
    'PK',
    'BD',
    'RU',
    'JP',
    'PH',
    'VN',
    'TR',
    'IR',
    'TH',
    'MM',
    'KR',
    'IQ',
    'AF',
    'MY',
    'NP',
    'DE',
    'FR',
    'GB',
    'IT',
    'ES',
    'UA',
    'PL',
    'RO',
    'NL',
    'GR',
    'HR',
    'BE',
    'PT',
    'CZ',
    'HU',
    'BY',
    'SE',
    'AT',
    'CH',
    'BG',
    'RS',
    'DK',
    'FI',
    'US',
    'MX',
    'CA',
    'GT',
    'CU',
    'HT',
    'DO',
    'HN',
    'NI',
    'SV',
    'CR',
    'PR',
    'PA',
    'JM',
    'TT',
    'GP',
    'MQ',
    'AU',
    'PG',
    'NZ',
    'FJ',
    'MU',
    'RE',
    'MV',
    'SC',
    'BR',
    'CO',
    'AR',
    'PE',
    'VE',
    'CL',
    'EC',
    'BO',
    'PY',
    'UY'
  ] as const
} as const;

export const STREETS_V8_FIELDS = {
  // ============ landuse ============
  landuse: {
    class: {
      values: [
        'aboriginal_lands',
        'agriculture',
        'airport',
        'cemetery',
        'commercial_area',
        'facility',
        'glacier',
        'grass',
        'hospital',
        'industrial',
        'park',
        'parking',
        'piste',
        'pitch',
        'residential',
        'rock',
        'sand',
        'school',
        'scrub',
        'wood'
      ] as const
    },
    type: {
      values: [
        'wood',
        'farmland',
        'forest',
        'grass',
        'meadow',
        'scrub',
        'parking',
        'surface',
        'park',
        'farmyard',
        'orchard',
        'grassland',
        'garden',
        'school',
        'soccer',
        'vineyard',
        'playground',
        'tennis',
        'bare_rock',
        'allotments',
        'pitch',
        'heath',
        'baseball',
        'bunker',
        'quarry',
        'beach',
        'basketball',
        'scree',
        'village_green',
        'recreation_ground',
        'sports_centre',
        'common',
        'christian',
        'tee',
        'sand',
        'green',
        'multi',
        'hospital',
        'greenhouse_horticulture',
        'glacier',
        'fairway',
        'farm',
        'golf_course',
        'camp_site',
        'university',
        'college',
        'plant_nursery',
        'equestrian',
        'fell',
        'beachvolleyball',
        'volleyball',
        'american_football',
        'athletics',
        'caravan_site',
        'rock',
        'muslim',
        'skateboard',
        'wetland',
        'bowls',
        'picnic_site',
        'boules',
        'cricket',
        'dog_park',
        'running',
        'conservation',
        'track',
        'netball',
        'underground',
        'lane',
        'rugby_union',
        'zoo',
        'hockey',
        'shooting',
        'downhill',
        'jewish',
        'field',
        'football',
        'table_tennis',
        'handball',
        'rough',
        'field_hockey',
        'team_handball',
        'carports',
        'pelota',
        'rugby',
        'paddle_tennis',
        'archery',
        'horse_racing',
        'gaelic_games',
        'softball',
        'golf',
        'ice_hockey',
        'basin',
        'coastline',
        'badminton',
        'driving_range',
        'bog',
        'cricket_nets',
        'swimming',
        'futsal'
      ] as const
    }
  },

  // ============ waterway ============
  waterway: {
    iso_3166_1: ISO_3166_1_FIELD,
    class: {
      values: [
        'river',
        'canal',
        'stream',
        'stream_intermittent',
        'ditch',
        'drain'
      ] as const
    },
    type: {
      values: [
        'river',
        'canal',
        'stream',
        'stream_intermittent',
        'ditch',
        'drain'
      ] as const
    }
  },

  // ============ water ============
  water: {},

  // ============ aeroway ============
  aeroway: {
    iso_3166_1: ISO_3166_1_FIELD,
    type: {
      values: ['runway', 'taxiway', 'apron', 'helipad'] as const
    }
  },

  // ============ structure ============
  structure: {
    iso_3166_1: ISO_3166_1_FIELD,
    class: {
      values: [
        'cliff',
        'crosswalk',
        'entrance',
        'fence',
        'gate',
        'hedge',
        'land',
        'steps',
        'tower'
      ] as const
    },
    type: {
      values: [
        'bollard',
        'breakwater',
        'bridge',
        'city_wall',
        'cliff',
        'crosswalk',
        'earth_bank',
        'entrance',
        'fence',
        'gate',
        'hedge',
        'home',
        'kissing_gate',
        'lift_gate',
        'main',
        'pier',
        'retaining_wall',
        'sliding_gate',
        'spikes',
        'staircase',
        'swing_gate',
        'wall',
        'wire_fence',
        'yes'
      ] as const
    }
  },

  // ============ building ============
  building: {
    iso_3166_1: ISO_3166_1_FIELD,
    extrude: {
      values: ['true', 'false'] as const
    },
    type: {
      values: [
        'building',
        'house',
        'residential',
        'garage',
        'apartments',
        'industrial',
        'hut',
        'detached',
        'shed',
        'roof',
        'commercial',
        'terrace',
        'garages',
        'school',
        'building:part',
        'retail',
        'construction',
        'greenhouse',
        'barn',
        'farm_auxiliary',
        'church',
        'warehouse',
        'service',
        'farm',
        'civic',
        'cabin',
        'manufacture',
        'university',
        'office',
        'static_caravan',
        'hangar',
        'public',
        'collapsed',
        'hospital',
        'semidetached_house',
        'hotel',
        'bungalow',
        'chapel',
        'ger',
        'kindergarten',
        'ruins',
        'parking',
        'storage_tank',
        'dormitory',
        'mosque',
        'commercial;residential',
        'transportation',
        'stable',
        'train_station',
        'damaged',
        'college',
        'semi',
        'transformer_tower',
        'houseboat',
        'trullo',
        'bunker',
        'station',
        'slurry_tank',
        'shop',
        'cowshed',
        'silo',
        'supermarket',
        'pajaru',
        'terminal',
        'carport',
        'residence',
        'dam',
        'temple',
        'duplex',
        'factory',
        'agricultural',
        'constructie',
        'allotment_house',
        'chalet',
        'kiosk',
        'tower',
        'tank',
        'shelter',
        'dwelling_house',
        'pavilion',
        'grandstand',
        'Residence',
        'ruin',
        'boathouse',
        'store',
        'summer_cottage',
        'mobile_home',
        'government_office',
        'outbuilding',
        'beach_hut',
        'pub',
        'glasshouse',
        'apartment',
        'storage',
        'community_group_office',
        'clinic',
        'residences',
        'cathedral',
        'bangunan',
        'semi-detached'
      ] as const
    },
    underground: {
      values: ['true', 'false'] as const
    }
  },

  // ============ landuse_overlay ============
  landuse_overlay: {
    class: {
      values: ['national_park', 'wetland', 'wetland_noveg'] as const
    },
    type: {
      values: [
        'wetland',
        'bog',
        'basin',
        'marsh',
        'swamp',
        'nature_reserve',
        'protected_area',
        'reedbed',
        'wet_meadow',
        'tidalflat',
        'mangrove',
        'mud',
        'saltmarsh',
        'national_park',
        'string_bog',
        'saltern',
        'fen',
        'palsa_bog',
        'tundra_pond',
        'peat_bog',
        'reed',
        'raised_bog',
        'reef'
      ] as const
    }
  },

  // ============ road ============
  road: {
    name_script: {
      values: [
        'Arabic',
        'Armenian',
        'Bengali',
        'Bopomofo',
        'Canadian_Aboriginal',
        'Common',
        'Cyrillic',
        'Devanagari',
        'Ethiopic',
        'Georgian',
        'Glagolitic',
        'Greek',
        'Gujarati',
        'Gurmukhi',
        'Han',
        'Hangul',
        'Hebrew',
        'Hiragana',
        'Kannada',
        'Katakana',
        'Khmer',
        'Lao',
        'Latin',
        'Malayalam',
        'Mongolian',
        'Myanmar',
        'Nko',
        'Sinhala',
        'Syriac',
        'Tamil',
        'Telugu',
        'Thaana',
        'Thai',
        'Tibetan',
        'Tifinagh',
        'Unknown'
      ] as const
    },
    oneway: {
      values: ['true', 'false'] as const
    },
    bike_lane: {
      values: ['left', 'right', 'both', 'no', 'yes'] as const
    },
    layer: {
      values: [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5] as const
    },
    access: {
      values: ['restricted'] as const
    },
    dual_carriageway: {
      values: ['true', 'false'] as const
    },
    structure: {
      values: ['none', 'bridge', 'tunnel', 'ford'] as const
    },
    surface: {
      values: ['paved', 'unpaved'] as const
    },
    shield: {
      values: [
        'default',
        'rectangle-white',
        'rectangle-red',
        'rectangle-orange',
        'rectangle-yellow',
        'rectangle-green',
        'rectangle-blue',
        'circle-white',
        'ae-national',
        'ae-d-route',
        'ae-f-route',
        'ae-s-route',
        'au-national-highway',
        'au-national-route',
        'au-state',
        'au-tourist',
        'br-federal',
        'br-state',
        'ch-motorway',
        'cn-nths-expy',
        'cn-provincial-expy',
        'de-motorway',
        'gr-motorway',
        'hk-strategic-route',
        'hr-motorway',
        'hu-motorway',
        'hu-main',
        'in-national',
        'in-state',
        'kr-natl-expy',
        'kr-natl-hwy',
        'kr-metro-expy',
        'kr-metropolitan',
        'kr-local',
        'mx-federal',
        'mx-state',
        'nz-state',
        'pe-national',
        'pe-regional',
        'ro-national',
        'ro-county',
        'ro-communal',
        'si-motorway',
        'tw-national',
        'tw-provincial-expy',
        'tw-provincial',
        'tw-county-township',
        'us-interstate',
        'us-interstate-duplex',
        'us-interstate-business',
        'us-interstate-truck',
        'us-highway',
        'us-highway-duplex',
        'us-highway-alternate',
        'us-highway-business',
        'us-highway-bypass',
        'us-highway-truck',
        'us-bia',
        'za-national',
        'za-provincial'
      ] as const
    },
    shield_beta: {
      values: [
        'default',
        'rectangle-white',
        'rectangle-red',
        'rectangle-orange',
        'rectangle-yellow',
        'rectangle-green',
        'rectangle-blue',
        'circle-white',
        'ae-national',
        'ae-d-route',
        'ae-f-route',
        'ae-s-route',
        'au-national-highway',
        'au-national-route',
        'au-state',
        'au-tourist',
        'br-federal',
        'br-state',
        'ch-motorway',
        'cn-nths-expy',
        'cn-provincial-expy',
        'de-motorway',
        'gr-motorway',
        'hk-strategic-route',
        'hr-motorway',
        'hu-motorway',
        'hu-main',
        'in-national',
        'in-state',
        'kr-natl-expy',
        'kr-natl-hwy',
        'kr-metro-expy',
        'kr-metropolitan',
        'kr-local',
        'mx-federal',
        'mx-state',
        'nz-state',
        'pe-national',
        'pe-regional',
        'ro-national',
        'ro-county',
        'ro-communal',
        'si-motorway',
        'tw-national',
        'tw-provincial-expy',
        'tw-provincial',
        'tw-county-township',
        'us-interstate',
        'us-interstate-duplex',
        'us-interstate-business',
        'us-interstate-truck',
        'us-highway',
        'us-highway-duplex',
        'us-highway-alternate',
        'us-highway-business',
        'us-highway-bypass',
        'us-highway-truck',
        'us-bia',
        'za-national',
        'za-provincial',
        'al-motorway',
        'ar-national',
        'cl-highway',
        'co-national',
        'cy-motorway',
        'il-highway-black',
        'il-highway-blue',
        'il-highway-green',
        'il-highway-red',
        'it-motorway',
        'md-local',
        'md-main',
        'my-expressway',
        'my-federal',
        'nz-urban',
        'ph-expressway',
        'ph-primary',
        'qa-main',
        'sa-highway',
        'th-highway',
        'th-motorway-toll',
        'tr-motorway'
      ] as const
    },
    shield_text_color: {
      values: ['black', 'blue', 'white', 'yellow', 'orange'] as const
    },
    shield_text_color_beta: {
      values: ['black', 'blue', 'white', 'yellow', 'red', 'green'] as const
    },
    iso_3166_1: ISO_3166_1_FIELD,
    class: {
      values: [
        'motorway',
        'motorway_link',
        'trunk',
        'trunk_link',
        'primary',
        'primary_link',
        'secondary',
        'secondary_link',
        'tertiary',
        'tertiary_link',
        'level_crossing',
        'street',
        'street_limited',
        'pedestrian',
        'construction',
        'track',
        'service',
        'ferry',
        'path',
        'major_rail',
        'minor_rail',
        'service_rail',
        'aerialway',
        'golf',
        'turning_circle',
        'roundabout',
        'mini_roundabout',
        'turning_loop',
        'traffic_signals',
        'intersection',
        'junction'
      ] as const
    },
    type: {
      values: [
        'motorway',
        'motorway_link',
        'trunk',
        'primary',
        'secondary',
        'tertiary',
        'trunk_link',
        'primary_link',
        'secondary_link',
        'tertiary_link',
        'residential',
        'unclassified',
        'road',
        'living_street',
        'level_crossing',
        'raceway',
        'pedestrian',
        'platform',
        'construction:motorway',
        'construction:motorway_link',
        'construction:trunk',
        'construction:trunk_link',
        'construction:primary',
        'construction:primary_link',
        'construction:secondary',
        'construction:secondary_link',
        'construction:tertiary',
        'construction:tertiary_link',
        'construction:unclassified',
        'construction:residential',
        'construction:road',
        'construction:living_street',
        'construction:pedestrian',
        'construction',
        'track:grade1',
        'track:grade2',
        'track:grade3',
        'track:grade4',
        'track:grade5',
        'track',
        'service:alley',
        'service:emergency_access',
        'service:drive_through',
        'service:driveway',
        'service:parking_aisle',
        'service',
        'ferry',
        'ferry_auto',
        'steps',
        'corridor',
        'sidewalk',
        'crossing',
        'piste',
        'mountain_bike',
        'hiking',
        'trail',
        'cycleway',
        'footway',
        'path',
        'bridleway',
        'rail',
        'subway',
        'narrow_gauge',
        'funicular',
        'light_rail',
        'miniature',
        'monorail',
        'preserved',
        'tram',
        'aerialway:cable_car',
        'aerialway:gondola',
        'aerialway:mixed_lift',
        'aerialway:chair_lift',
        'aerialway:drag_lift',
        'aerialway:magic_carpet',
        'aerialway',
        'hole',
        'turning_circle',
        'mini_roundabout',
        'traffic_signals'
      ] as const
    },
    toll: {
      values: ['true'] as const
    }
  },

  // ============ admin ============
  admin: {
    admin_level: {
      values: [0, 1, 2] as const
    },
    disputed: {
      values: ['true', 'false'] as const
    },
    iso_3166_1: ISO_3166_1_FIELD,
    maritime: {
      values: ['true', 'false'] as const
    },
    worldview: {
      values: ['JP', 'CN', 'IN', 'US', 'all'] as const
    }
  },

  // ============ place_label ============
  place_label: {
    class: {
      values: [
        'country',
        'disputed_country',
        'state',
        'settlement',
        'disputed_settlement',
        'settlement_subdivision',
        'disputed_settlement_subdivision'
      ] as const
    },
    name_script: {
      values: [
        'Arabic',
        'Armenian',
        'Bengali',
        'Bopomofo',
        'Canadian_Aboriginal',
        'Common',
        'Cyrillic',
        'Devanagari',
        'Ethiopic',
        'Georgian',
        'Glagolitic',
        'Greek',
        'Gujarati',
        'Gurmukhi',
        'Han',
        'Hangul',
        'Hebrew',
        'Hiragana',
        'Kannada',
        'Katakana',
        'Khmer',
        'Lao',
        'Latin',
        'Malayalam',
        'Mongolian',
        'Myanmar',
        'Nko',
        'Sinhala',
        'Syriac',
        'Tamil',
        'Telugu',
        'Thaana',
        'Thai',
        'Tibetan',
        'Tifinagh',
        'Unknown'
      ] as const
    },
    filterrank: {
      values: [0, 1, 2, 3, 4, 5] as const
    },
    capital: {
      values: [2, 3, 4, 5, 6] as const
    },
    text_anchor: {
      values: [
        'center',
        'left',
        'right',
        'top',
        'top-left',
        'top-right',
        'bottom',
        'bottom-left',
        'bottom-right'
      ] as const
    },
    symbolrank: {
      values: [
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18
      ] as const
    },
    type: {
      values: [
        'country',
        'territory',
        'sar',
        'disputed_territory',
        'state',
        'city',
        'town',
        'village',
        'hamlet',
        'suburb',
        'neighbourhood',
        'quarter',
        'block'
      ] as const
    },
    iso_3166_1: ISO_3166_1_FIELD,
    worldview: {
      values: ['JP', 'CN', 'IN', 'US', 'all'] as const
    }
  },

  // ============ airport_label ============
  airport_label: {
    class: {
      values: ['military', 'civil'] as const
    },
    name_script: {
      values: [
        'Arabic',
        'Armenian',
        'Bengali',
        'Bopomofo',
        'Canadian_Aboriginal',
        'Common',
        'Cyrillic',
        'Devanagari',
        'Ethiopic',
        'Georgian',
        'Glagolitic',
        'Greek',
        'Gujarati',
        'Gurmukhi',
        'Han',
        'Hangul',
        'Hebrew',
        'Hiragana',
        'Kannada',
        'Katakana',
        'Khmer',
        'Lao',
        'Latin',
        'Malayalam',
        'Mongolian',
        'Myanmar',
        'Nko',
        'Sinhala',
        'Syriac',
        'Tamil',
        'Telugu',
        'Thaana',
        'Thai',
        'Tibetan',
        'Tifinagh',
        'Unknown'
      ] as const
    },
    maki: {
      values: ['airport', 'heliport', 'rocket', 'airfield'] as const
    },
    sizerank: {
      values: [
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
      ] as const
    },
    worldview: {
      values: ['JP', 'CN', 'IN', 'US', 'all'] as const
    },
    iso_3166_1: ISO_3166_1_FIELD
  },

  // ============ transit_stop_label ============
  transit_stop_label: {
    name_script: {
      values: [
        'Arabic',
        'Armenian',
        'Bengali',
        'Bopomofo',
        'Canadian_Aboriginal',
        'Common',
        'Cyrillic',
        'Devanagari',
        'Ethiopic',
        'Georgian',
        'Glagolitic',
        'Greek',
        'Gujarati',
        'Gurmukhi',
        'Han',
        'Hangul',
        'Hebrew',
        'Hiragana',
        'Kannada',
        'Katakana',
        'Khmer',
        'Lao',
        'Latin',
        'Malayalam',
        'Mongolian',
        'Myanmar',
        'Nko',
        'Sinhala',
        'Syriac',
        'Tamil',
        'Telugu',
        'Thaana',
        'Thai',
        'Tibetan',
        'Tifinagh',
        'Unknown'
      ] as const
    },
    mode: {
      values: [
        'metro_rail',
        'rail',
        'light_rail',
        'tram',
        'monorail',
        'funicular',
        'bicycle',
        'bus',
        'ferry'
      ] as const
    },
    stop_type: {
      values: ['stop', 'station', 'entrance'] as const
    },
    maki: {
      values: [
        'bus',
        'rail',
        'rail-light',
        'entrance',
        'ferry',
        'bicycle-share',
        'rail-metro'
      ] as const
    },
    network: {
      values: [
        'barcelona-metro',
        'boston-t',
        'chongqing-rail-transit',
        'de-s-bahn',
        'de-s-bahn.de-u-bahn',
        'de-u-bahn',
        'delhi-metro',
        'gb-national-rail',
        'gb-national-rail.london-dlr',
        'gb-national-rail.london-dlr.london-overground.london-tfl-rail.london-underground',
        'gb-national-rail.london-dlr.london-overground.london-underground',
        'gb-national-rail.london-dlr.london-underground',
        'gb-national-rail.london-overground',
        'gb-national-rail.london-overground.london-underground',
        'gb-national-rail.london-overground.london-tfl-rail.london-underground',
        'gb-national-rail.london-tfl-rail',
        'gb-national-rail.london-tfl-rail.london-overground',
        'gb-national-rail.london-tfl-rail.london-underground',
        'gb-national-rail.london-underground',
        'hong-kong-mtr',
        'kiev-metro',
        'london-dlr',
        'london-dlr.london-tfl-rail',
        'london-dlr.london-tfl-rail.london-underground',
        'london-dlr.london-underground',
        'london-overground',
        'london-overground.london-tfl-rail',
        'london-overground.london-tfl-rail.london-underground',
        'london-overground.london-underground',
        'london-tfl-rail',
        'london-tfl-rail.london-underground',
        'london-underground',
        'madrid-metro',
        'mexico-city-metro',
        'milan-metro',
        'moscow-metro',
        'new-york-subway',
        'osaka-subway',
        'oslo-metro',
        'paris-metro',
        'paris-metro.paris-rer',
        'paris-rer',
        'paris-rer.paris-transilien',
        'paris-transilien',
        'philadelphia-septa',
        'san-francisco-bart',
        'singapore-mrt',
        'stockholm-metro',
        'taipei-metro',
        'tokyo-metro',
        'vienna-u-bahn',
        'washington-metro',
        'rail',
        'rail-metro',
        'rail-light',
        'entrance',
        'bus',
        'ferry',
        'bicycle-share'
      ] as const
    },
    network_beta: {
      values: [
        'jp-shinkansen',
        'jp-shinkansen.jp-jr',
        'jp-shinkansen.tokyo-metro',
        'jp-shinkansen.osaka-subway',
        'jp-shinkansen.jp-jr.tokyo-metro',
        'jp-shinkansen.jp-jr.osaka-subway',
        'jp-jr',
        'jp-jr.tokyo-metro',
        'jp-jr.osaka-subway'
      ] as const
    },
    iso_3166_1: ISO_3166_1_FIELD,
    filterrank: {
      values: [0, 1, 2, 3, 4, 5] as const
    }
  },

  // ============ natural_label ============
  natural_label: {
    iso_3166_1: ISO_3166_1_FIELD,
    name_script: {
      values: [
        'Arabic',
        'Armenian',
        'Bengali',
        'Bopomofo',
        'Canadian_Aboriginal',
        'Common',
        'Cyrillic',
        'Devanagari',
        'Ethiopic',
        'Georgian',
        'Glagolitic',
        'Greek',
        'Gujarati',
        'Gurmukhi',
        'Han',
        'Hangul',
        'Hebrew',
        'Hiragana',
        'Kannada',
        'Katakana',
        'Khmer',
        'Lao',
        'Latin',
        'Malayalam',
        'Mongolian',
        'Myanmar',
        'Nko',
        'Sinhala',
        'Syriac',
        'Tamil',
        'Telugu',
        'Thaana',
        'Thai',
        'Tibetan',
        'Tifinagh',
        'Unknown'
      ] as const
    },
    sizerank: {
      values: [
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
      ] as const
    },
    class: {
      values: [
        'ocean',
        'disputed_ocean',
        'sea',
        'disputed_sea',
        'water',
        'disputed_water',
        'reservoir',
        'disputed_reservoir',
        'river',
        'disputed_river',
        'bay',
        'disputed_bay',
        'dock',
        'disputed_dock',
        'canal',
        'disputed_canal',
        'stream',
        'disputed_stream',
        'landform',
        'disputed_landform',
        'wetland',
        'disputed_wetland',
        'water_feature',
        'disputed_water_feature',
        'glacier',
        'disputed_glacier',
        'continent'
      ] as const
    },
    maki: {
      values: ['marker', 'waterfall', 'volcano', 'mountain'] as const
    },
    filterrank: {
      values: [0, 1, 2, 3, 4, 5] as const
    },
    disputed: {
      values: ['true', 'false'] as const
    },
    worldview: {
      values: ['JP', 'CN', 'IN', 'US', 'all'] as const
    }
  },

  // ============ poi_label ============
  poi_label: {
    name_script: {
      values: [
        'Arabic',
        'Armenian',
        'Bengali',
        'Bopomofo',
        'Canadian_Aboriginal',
        'Common',
        'Cyrillic',
        'Devanagari',
        'Ethiopic',
        'Georgian',
        'Glagolitic',
        'Greek',
        'Gujarati',
        'Gurmukhi',
        'Han',
        'Hangul',
        'Hebrew',
        'Hiragana',
        'Kannada',
        'Katakana',
        'Khmer',
        'Lao',
        'Latin',
        'Malayalam',
        'Mongolian',
        'Myanmar',
        'Nko',
        'Sinhala',
        'Syriac',
        'Tamil',
        'Telugu',
        'Thaana',
        'Thai',
        'Tibetan',
        'Tifinagh',
        'Unknown'
      ] as const
    },
    maki: {
      values: [
        'amusement-park',
        'aquarium',
        'art-gallery',
        'attraction',
        'cinema',
        'casino',
        'museum',
        'stadium',
        'theatre',
        'zoo',
        'marker',
        'bank',
        'bicycle',
        'car-rental',
        'laundry',
        'suitcase',
        'veterinary',
        'college',
        'school',
        'bar',
        'beer',
        'cafe',
        'fast-food',
        'ice-cream',
        'restaurant',
        'restaurant-noodle',
        'restaurant-pizza',
        'restaurant-seafood',
        'alcohol-shop',
        'bakery',
        'grocery',
        'convenience',
        'confectionery',
        'castle',
        'monument',
        'harbor',
        'farm',
        'bridge',
        'communications-tower',
        'watermill',
        'windmill',
        'lodging',
        'dentist',
        'doctor',
        'hospital',
        'pharmacy',
        'fuel',
        'car-repair',
        'charging-station',
        'parking',
        'parking-garage',
        'campsite',
        'cemetery',
        'dog-park',
        'garden',
        'golf',
        'park',
        'picnic-site',
        'playground',
        'embassy',
        'fire-station',
        'library',
        'police',
        'post',
        'prison',
        'town-hall',
        'place-of-worship',
        'religious-buddhist',
        'religious-christian',
        'religious-jewish',
        'religious-muslim',
        'viewpoint',
        'horse-riding',
        'swimming',
        'beach',
        'american-football',
        'basketball',
        'tennis',
        'table-tennis',
        'volleyball',
        'bowling-alley',
        'slipway',
        'pitch',
        'fitness-centre',
        'skateboard',
        'car',
        'clothing-store',
        'furniture',
        'hardware',
        'globe',
        'jewelry-store',
        'mobile-phone',
        'optician',
        'shoe',
        'watch',
        'shop',
        'music',
        'drinking-water',
        'information',
        'toilet',
        'ranger-station'
      ] as const
    },
    maki_beta: {
      values: [
        'baseball',
        'lighthouse',
        'landmark',
        'industry',
        'highway-services',
        'highway-rest-area',
        'racetrack-cycling',
        'racetrack-horse',
        'racetrack-boat',
        'racetrack',
        'religious-shinto',
        'observation-tower',
        'restaurant-bbq',
        'tunnel'
      ] as const
    },
    maki_modifier: {
      values: ['JP'] as const
    },
    class: {
      values: [
        'arts_and_entertainment',
        'building',
        'commercial_services',
        'education',
        'food_and_drink',
        'food_and_drink_stores',
        'historic',
        'industrial',
        'landmark',
        'lodging',
        'medical',
        'motorist',
        'park_like',
        'place_like',
        'public_facilities',
        'religion',
        'sport_and_leisure',
        'store_like',
        'visitor_amenities',
        'general'
      ] as const
    },
    type: {
      values: [
        'Parking',
        'Locality',
        'Yes',
        'School',
        'Restaurant',
        'Place Of Worship',
        'Pitch',
        'Swimming Pool',
        'Retail',
        'Playground',
        'Convenience',
        'Residential',
        'Park',
        'Fuel',
        'Fast Food',
        'Isolated Dwelling',
        'Cafe',
        'Supermarket',
        'Cemetery',
        'Hotel',
        'Bank',
        'Industrial',
        'Pharmacy',
        'Clothes',
        'Guidepost',
        'Allotments',
        'Hospital',
        'Apartments',
        'Kindergarten',
        'Toilets',
        'Memorial',
        'Hairdresser',
        'Car Repair',
        'Bar',
        'Commercial',
        'Bakery',
        'Government',
        'Board',
        'Bridge',
        'House',
        'Company',
        'Grave Yard',
        'Drinking Water',
        'Post Office',
        'Pub',
        'Clinic',
        'Beach',
        'Guest House',
        'Sports Centre',
        'Attraction',
        'Viewpoint',
        'Doctors',
        'Car',
        'Townhall',
        'Police',
        'Fire Station',
        'University',
        'Camp Site',
        'Picnic Site',
        'Beauty',
        'Community Centre',
        'Dentist',
        'Works',
        'Library',
        'Shinto',
        'Museum',
        'Social Facility',
        'Wood',
        'Nature Reserve',
        'Mobile Phone',
        'Information',
        'Hardware',
        'Furniture',
        'Buddhist',
        'Chalet',
        'Electronics',
        'Marketplace',
        'Butcher',
        'College',
        'Forest',
        'Mall',
        'Estate Agent',
        'Shoes',
        'Alcohol',
        'Florist',
        'Archaeological Site',
        'Picnic Table',
        'Ruins',
        'Doityourself',
        'Fitness Centre',
        'Car Parts',
        'Monument',
        'Map',
        'Optician',
        'Office',
        'Jewelry',
        'Variety Store',
        'Hostel',
        'Construction',
        'Insurance'
      ] as const
    },
    brand: {
      values: [
        '21rentacar',
        '2nd-street',
        '31-ice-cream',
        '7-eleven',
        'aen',
        'aeon',
        'aiya',
        'alpen',
        'aoki',
        'aoyama',
        'asakuma',
        'atom',
        'audi',
        'autobacs',
        'b-kids',
        'bamiyan',
        'barneys-newyork',
        'benz',
        'best-denki',
        'big-boy',
        'bikkuri-donkey',
        'bmw',
        'bon-belta',
        'book-off',
        'budget',
        'carenex',
        'casa',
        'citroen',
        'cockpit',
        'coco-ichibanya',
        'cocos',
        'community-store',
        'cosmo-oil',
        'costco',
        'daiei',
        'daihatsu',
        'daily-store',
        'daimaru',
        'daiwa',
        'dennys',
        'dio',
        'doutor-coffee',
        'eki-rent-a-car',
        'eneos',
        'f-rent-a-car',
        'familymart',
        'ferrari',
        'fiat',
        'forus',
        'fukudaya-department-store',
        'fukuya',
        'futata',
        'garage-off',
        'general-motors',
        'gmdat',
        'grache-gardens',
        'gulliver',
        'gusto',
        'hamacho',
        'hamazushi',
        'hamburg-restaurant-bell',
        'hankyu-department-store',
        'hanshin',
        'hard-off',
        'haruyama',
        'heisei-car',
        'heiwado',
        'hihirose',
        'hino',
        'hobby-off',
        'hokuren',
        'honda',
        'honda-cars',
        'ichibata-department-store',
        'idemitsu-oil',
        'inageya',
        'isetan',
        'isuzu',
        'ito-yokado',
        'iwataya',
        'izumi',
        'izumiya',
        'izutsuya',
        'j-net-rentcar',
        'ja-ss',
        'jaguar',
        'japan-post-bank',
        'japan-post-insurance',
        'japan-rent-a-car',
        'jolly-ox',
        'jolly-pasta',
        'jonathans',
        'joyfull',
        'jumble-store',
        'kaisen-misakiko',
        'kasumi',
        'kawatoku',
        'keihan-department-store',
        'keio-department-store',
        'kfc',
        'kintetsu-department-store',
        'kygnus-oil',
        'kyubeiya',
        'laforet-harajuku',
        'lamborghini',
        'lamu',
        'landrover',
        'lawson',
        'lexus',
        'life',
        'lotteria',
        'lumine',
        'maruetsu',
        'maruetsupetit',
        'maruhiro-department-store',
        'maruhoncowboy',
        'marui',
        'marunen-me',
        'matsubishi',
        'matsuya',
        'matsuya-department-store',
        'matsuyadenki',
        'matsuzakaya',
        'mazda-autozam',
        'mazda-enfini',
        'mcdonalds',
        'meitetsu-pare-department-store',
        'melsa',
        'michi-no-eki',
        'milky-way',
        'mini',
        'mini-piago',
        'ministop',
        'mitsubishi-corporation-energy',
        'mitsubishi-fuso',
        'mitsubishi-motors',
        'mitsukoshi',
        'mizuho-bank',
        'mode-off',
        'mos-burger',
        'mufg-bank',
        'my-basket',
        'nagasakiya',
        'nakago',
        'nakasan',
        'nakau',
        'natural-lawson',
        'navi',
        'netz-toyota',
        'niconicorentacar',
        'nippo-rent-a-car-system',
        'nippon-rent-a-car',
        'nissan',
        'nissan-cherry',
        'nissan-motor',
        'nissan-parts',
        'nissan-prince',
        'nissan-rent-a-car',
        'nissan-satio',
        'odakyu-department-store',
        'off-house',
        'ohsho',
        'oita-rental',
        'ok',
        'okajima',
        'okuno',
        'okuwa',
        'onuma',
        'orix-rent-a-car',
        'osaka-ohsho',
        'ots-rentacar',
        'palty-fuji',
        'parco',
        'petras',
        'peugeot',
        'plaka',
        'poplar',
        'popolo',
        'pork-cutlet-hamakatsu',
        'porsche',
        'ralse',
        'recycle-mart',
        'red-cabbage',
        'red-lobster',
        'renault',
        'resona-bank',
        'ringer-hut',
        'rolls-royce',
        'royal-host',
        'saga-rent-lease',
        'saijo-department-store',
        'saikaya',
        'saint-marc',
        'saitama-resona-bank',
        'saizeriya',
        'sanbangai',
        'sanei',
        'santa-no-souko',
        'sato',
        'seibu',
        'seicomart',
        'seiyu',
        'shabushabu-dontei',
        'shinkin-bank',
        'showa-shell-oil',
        'sizzler',
        'sky-rentallease',
        'smile-santa',
        'sogo',
        'sokoseikatsukan',
        'solato',
        'starbucks-coffee',
        'steak-hamburg-ken',
        'steak-miya',
        'steak-no-don',
        'store100',
        'subaru',
        'suehiro',
        'sukiya',
        'sumitomo-mitsui-banking-corporation',
        'sunpiazza',
        'sushihan',
        'suzuki',
        'suzuran-department-store',
        'tachiya',
        'taiyakan',
        'takarajima',
        'takashimaya',
        'tamaya',
        'tenmaya',
        'times-car-rental',
        'tobu-department-store',
        'tokiwa',
        'tokyu-department-store',
        'tokyu-store',
        'tomato-onion',
        'tonden',
        'toyopet',
        'toyota',
        'toyota-corolla',
        'toyota-parts',
        'toyota-rent-a-car',
        'tsuruya-department-store',
        'tullys-coffee',
        'ud-trucks',
        'victoria',
        'victoria-station',
        'vivre',
        'volks',
        'volkswagen',
        'volvo',
        'yamakataya',
        'yamazaki-shop',
        'yanase',
        'yao-department-store',
        'yayoiken',
        'yellow-hat',
        'york-benimaru',
        'yoshinoya',
        'you-me-mart',
        'yumean',
        'zenrin'
      ] as const
    },
    category_en: {
      values: [
        'Locality',
        'School Grounds',
        'Swimming Pool',
        'Restaurant',
        'Park',
        'Church',
        'Shop',
        'Playground',
        'Sport Pitch',
        'Convenience Store',
        'Gas Station',
        'Supermarket',
        'Cafe',
        'Cemetery',
        'Bank',
        'Fast Food',
        'Hotel',
        'Isolated Dwelling',
        'Retail Building',
        'Guidepost',
        'Pharmacy',
        'Residential Area',
        'Community Garden',
        'Clothing Store',
        'Kindergarten',
        'Information Board',
        'Graveyard',
        'Memorial',
        'Apartments',
        'Hospital Grounds',
        'Pub',
        'Post Office',
        'Bar',
        'House',
        'Bakery',
        'Industrial Area',
        'Car Repair Shop',
        'Mosque',
        'Place of Worship',
        'Viewpoint',
        'Sports Complex',
        'Police',
        'Beach',
        'Picnic Site',
        'Tourist Attraction',
        'Guest House',
        'Town Hall',
        'Car Parking',
        'Fire Station',
        'Campground',
        'Car Dealership',
        "Doctor's Office",
        'Residential Building',
        'Community Center',
        'Library',
        'Museum',
        'Clinic',
        'Information',
        'Dentist',
        'Social Facility',
        'Monument',
        'Hardware Store',
        'Butcher',
        'Wood',
        'Furniture Store',
        'Florist',
        'Marketplace',
        'University Grounds',
        'Electronics Store',
        'DIY Store',
        'Mall',
        'College Grounds',
        'Shoe Store',
        'Mobile Phone Store',
        'University Building',
        'Archaeological Site',
        'Liquor Store',
        'Quarry',
        'Stadium',
        'Commercial Area',
        'Tower',
        'Buddhist Temple',
        'Hostel',
        'Castle',
        'Factory',
        'Bridge',
        'Ruins',
        'Department Store',
        'Motel',
        'Book Store',
        'Jeweler',
        'Optician',
        'Golf Course',
        'Holiday Cottage',
        'Gift Shop',
        'Farmland',
        'Bicycle Shop',
        'Greengrocer',
        'Theater',
        'Retail Area'
      ] as const
    },
    'category_zh-Hans': {
      values: [
        '地方',
        '学校',
        '游泳池',
        '餐馆',
        '公园',
        '基督教堂',
        '商店',
        '墓地',
        '儿童游乐场',
        '运动场地',
        '便利店',
        '加油站',
        '超市',
        '咖啡馆',
        '银行',
        '快餐店',
        '宾馆',
        '孤立居所',
        '零售业建筑',
        '路标',
        '药房',
        '居民区',
        '公共花园',
        '服装店',
        '幼儿园',
        '信息板',
        '纪念碑',
        '住宅楼',
        '诊所',
        '医院',
        '酒馆',
        '邮局',
        '酒吧',
        '房屋',
        '面包店',
        '工业区',
        '汽车修理店',
        '清真寺',
        '礼拜场所',
        '观景点',
        '体育中心/综合体育场',
        '警察局',
        '海滩',
        '野餐地',
        '旅游名胜',
        '小旅馆',
        '政府办公大楼',
        '停车场',
        '消防站',
        '宿营场地',
        '汽车店',
        '住宅建筑物',
        '社区中心',
        '图书馆',
        '博物馆',
        '游客中心',
        '牙科医院',
        '社会服务设施',
        '纪念堂',
        '五金店',
        '肉店',
        '树林',
        '家具店',
        '花店',
        '鞋店',
        '市场',
        '大学',
        '电子产品店',
        'DIY店',
        '购物中心',
        '学院',
        '手机店',
        '大学建筑',
        '考古遗址',
        '外卖酒店',
        '露天矿场',
        '体育场',
        '商业区',
        '塔',
        '佛教寺庙',
        '旅舍',
        '城堡',
        '工厂',
        '桥梁',
        '遗迹',
        '百货商场',
        '汽车旅馆',
        '书店',
        '珠宝店',
        '眼镜店',
        '高尔夫球场',
        '度假屋',
        '礼品店',
        '自行车店',
        '蔬果店',
        '剧院',
        '零售商店',
        '兽医院',
        '旅行社',
        '绿地'
      ] as const
    },
    iso_3166_1: ISO_3166_1_FIELD,
    sizerank: {
      values: [
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16
      ] as const
    },
    filterrank: {
      values: [0, 1, 2, 3, 4, 5] as const
    },
    disputed: {
      values: ['true', 'false'] as const
    }
  },

  // ============ motorway_junction ============
  motorway_junction: {
    iso_3166_1: ISO_3166_1_FIELD,
    class: {
      values: [
        'motorway',
        'motorway_link',
        'trunk',
        'trunk_link',
        'primary',
        'secondary',
        'tertiary',
        'primary_link',
        'secondary_link',
        'tertiary_link',
        'street',
        'street_limited',
        'construction',
        'track',
        'service',
        'path',
        'major_rail',
        'minor_rail',
        'service_rail'
      ] as const
    },
    type: {
      values: [
        'motorway',
        'trunk',
        'motorway_link',
        'primary',
        'trunk_link',
        'secondary',
        'tertiary',
        'primary_link',
        'secondary_link',
        'tertiary_link'
      ] as const
    },
    maki_beta: {
      values: ['interchange', 'junction'] as const
    },
    filterrank: {
      values: [0, 1, 2, 3, 4, 5] as const
    }
  },

  // ============ housenum_label ============
  housenum_label: {
    iso_3166_1: ISO_3166_1_FIELD
  }
} as const;

export type SourceLayer = keyof typeof STREETS_V8_FIELDS;
